import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Helper: Smart text wrapping at word boundaries
function wrapText(text: string, maxCharsPerLine: number): string[] {
    const words = text.split(' ');
    const lines: string[] = [];
    let currentLine = '';

    for (const word of words) {
        const testLine = currentLine ? `${currentLine} ${word}` : word;
        if (testLine.length <= maxCharsPerLine) {
            currentLine = testLine;
        } else {
            if (currentLine) lines.push(currentLine);
            currentLine = word;
        }
    }
    if (currentLine) lines.push(currentLine);
    return lines;
}

serve(async (req) => {
    if (req.method === "OPTIONS") {
        return new Response(null, { headers: corsHeaders });
    }

    try {
        const {
            imageSource,
            imageUrl,
            aiPrompt,
            text,
            style = { primaryColor: '#004F8F', accentColor: '#1A7A3E' }
        } = await req.json();

        const GCP_PROJECT_ID = Deno.env.get("GCP_PROJECT_ID");
        const GCP_REGION = Deno.env.get("GCP_REGION");
        const VERTEX_API_KEY = Deno.env.get("VERTEX_API_KEY");

        let baseImageUrl = imageUrl;

        // If AI-generated, call Vertex AI
        if (imageSource === 'ai-generated' && aiPrompt) {
            if (!GCP_PROJECT_ID || !GCP_REGION || !VERTEX_API_KEY) {
                throw new Error("Vertex AI not configured");
            }

            const vertexUrl = `https://${GCP_REGION}-aiplatform.googleapis.com/v1/projects/${GCP_PROJECT_ID}/locations/${GCP_REGION}/publishers/google/models/imagen-3.0-generate-001:predict?key=${VERTEX_API_KEY}`;

            const imageSystemPrompt = `You are a professional photographer for Lifetrek Medical.
CRITICAL RULE: DO NOT GENERATE ANY TEXT OR LOGOS.
Your job is to generate purely visual SCENES.

BRAND COLORS:
- Backgrounds: White, Light Grey, Corporate Blue (#004F8F) tinting.
- Accents: Innovation Green (#1A7A3E)

VISUAL STYLE:
- Photorealistic or High-End 3D
- Clean, sterile, precision medical environment
- NO HUMANS necessary
- Detailed machinery or clean facilities`;

            const imageResponse = await fetch(vertexUrl, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    instances: [{ prompt: `SYSTEM: ${imageSystemPrompt}\nUSER REQUEST: ${aiPrompt}` }],
                    parameters: { sampleCount: 1, aspectRatio: "1:1" }
                }),
            });

            if (!imageResponse.ok) {
                throw new Error(`Vertex AI failed: ${imageResponse.status}`);
            }

            const imageData = await imageResponse.json();
            const b64Image = imageData.predictions?.[0]?.bytesBase64Encoded;

            if (!b64Image) {
                throw new Error("No image generated by Vertex AI");
            }

            baseImageUrl = `data:image/png;base64,${b64Image}`;
        }

        if (!baseImageUrl) {
            throw new Error("No image source provided");
        }

        // For Deno Edge Functions, we can't use sharp directly
        // Instead, we'll use imagescript or return SVG overlay instructions
        // For now, return the compositing parameters for client-side processing

        const WIDTH = 1080;
        const HEIGHT = 1080;

        // Determine text position
        const position = text.position === 'auto'
            ? (Math.random() > 0.5 ? 'bottom' : 'top')
            : text.position;

        const isBottomText = position === 'bottom';

        // Wrap text
        const headlineLines = wrapText(text.headline, 20);
        const subheadLines = wrapText(text.subhead, 50);

        // Calculate positions
        const headlineY = isBottomText ? 800 : 200;
        const accentY = isBottomText ? 850 : 250;
        const subheadY = isBottomText ? 930 : 330;
        const logoY = isBottomText ? 40 : 950;

        // Build tspans
        const headlineTspans = headlineLines.map((line, i) =>
            i === 0
                ? `<tspan x="540" dy="0">${line}</tspan>`
                : `<tspan x="540" dy="1.1em">${line}</tspan>`
        ).join('\n        ');

        const subheadTspans = subheadLines.slice(0, 2).map((line, i) =>
            i === 0
                ? `<tspan x="540" dy="0">${line}</tspan>`
                : `<tspan x="540" dy="1.4em">${line}</tspan>`
        ).join('\n        ');

        // Generate gradient SVG
        const gradientSvg = `<svg width="${WIDTH}" height="${HEIGHT}">
      <defs>
        <linearGradient id="textGrad" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="25%" style="stop-color:${style.primaryColor};stop-opacity:0" />
          <stop offset="55%" style="stop-color:${style.primaryColor};stop-opacity:0.4" />
          <stop offset="100%" style="stop-color:${style.primaryColor};stop-opacity:1" />
        </linearGradient>
      </defs>
      <rect x="0" y="0" width="${WIDTH}" height="${HEIGHT}" fill="url(#textGrad)" />
    </svg>`;

        // Generate text overlay SVG
        const textSvg = `<svg width="${WIDTH}" height="${HEIGHT}">
      <style>
        .headline { 
          fill: white; 
          font-family: Arial, sans-serif; 
          font-weight: 900; 
          font-size: 95px; 
          text-anchor: middle; 
          text-transform: uppercase; 
          filter: drop-shadow(0px 4px 12px rgba(0,0,0,0.7)); 
        }
        .subhead { 
          fill: #ffffff; 
          font-family: Arial, sans-serif; 
          font-weight: 500; 
          font-size: 38px; 
          text-anchor: middle; 
          filter: drop-shadow(0px 3px 6px rgba(0,0,0,0.5));
        }
        .accent { fill: ${style.accentColor}; }
      </style>
      
      <text x="540" y="${headlineY}" class="headline">
        ${headlineTspans}
      </text>
      
      <rect x="300" y="${accentY}" width="480" height="5" class="accent" />
      
      <text x="540" y="${subheadY}" class="subhead">
        ${subheadTspans}
      </text>
    </svg>`;

        // Return compositing instructions
        const result = {
            baseImage: baseImageUrl,
            overlays: {
                gradient: `data:image/svg+xml;base64,${btoa(gradientSvg)}`,
                text: `data:image/svg+xml;base64,${btoa(textSvg)}`,
            },
            logoPosition: { x: WIDTH - 180, y: logoY },
            metadata: {
                width: WIDTH,
                height: HEIGHT,
                textPosition: position
            }
        };

        return new Response(
            JSON.stringify(result),
            { headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );

    } catch (error) {
        console.error("Error in composite-carousel-image:", error);
        return new Response(
            JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
            { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 500 }
        );
    }
});
