const fs = require('fs');
const path = require('path');
// Check if modules exist, if not try to handle gracefully or log error
let parse, stringify;
try {
  parse = require('csv-parse/sync').parse;
  stringify = require('csv-stringify/sync').stringify;
} catch (e) {
  fs.writeFileSync(path.join(process.cwd(), 'execution', 'error.log'), `Module Load Error: ${e.message}\nStack: ${e.stack}`);
  process.exit(1);
}

const INPUT_FILE = path.join(process.cwd(), 'execution', 'FINAL_LEADS_FOR_UPLOAD.csv');
const OUTPUT_FILE = path.join(process.cwd(), 'execution', 'RANKED_LEADS_HEATMAP.csv');
const SUMMARY_FILE = path.join(process.cwd(), 'execution', 'LEADS_SUMMARY.md');
const ERROR_FILE = path.join(process.cwd(), 'execution', 'error.log');

const OWNERSHIP_RULES = {
  MARCIO: [
    "Implantes Odontológicos",
    "Implantes Ortopédicos",
    "Implantes Veterinários",
    "Ferramental Customizado",
    "Peças de Micro Precisão",
    "Implantes Espinhais",
    "Veterinário Ortopedia"
  ],
  VANESSA: [
    "Equipamentos Odontológicos",
    "Instrumentos Cirúrgicos",
    "Dispositivos Médicos",
    "Materiais Odontológicos",
    "Distribuidor",
    "Distribuidor Ortopedia",
    "Materiais Consumo",
    "Equipamentos Hospitalares",
    "Instrumentos Odontológicos",
    "Materiais Hospitalares",
    "Equipamentos Médicos",
    "Dispositivos Eletrônicos",
    "MedTech Software",
    "Dispositivos Diagnóstico"
  ]
};

function determineHeatmapCategory(score) {
  if (score >= 9.0) return 'HOT 🔥';
  if (score >= 7.0 && score < 9.0) return 'WARM ⚠️';
  return 'COLD ❄️';
}

function determineOwner(segment) {
  if (!segment) return 'Unassigned';
  const normalizedSegment = segment.trim();

  if (OWNERSHIP_RULES.MARCIO.includes(normalizedSegment)) return 'Márcio';
  if (OWNERSHIP_RULES.VANESSA.includes(normalizedSegment)) return 'Vanessa';
  
  const lowerSeg = normalizedSegment.toLowerCase();
  if (lowerSeg.includes('implante') || lowerSeg.includes('industrial') || lowerSeg.includes('ferramental')) return 'Márcio';
  if (lowerSeg.includes('equipamento') || lowerSeg.includes('distribuidor') || lowerSeg.includes('comércio') || lowerSeg.includes('hospitalar')) return 'Vanessa';

  return 'Unassigned';
}

async function main() {
  try {
    if (!fs.existsSync(INPUT_FILE)) {
      throw new Error(`Input file not found: ${INPUT_FILE}`);
    }

    const fileContent = fs.readFileSync(INPUT_FILE, 'utf-8');
    const records = parse(fileContent, {
      columns: true,
      skip_empty_lines: true
    });

    const rankedLeads = records.map((record) => {
      let score = 0;
      if (record.v2_score) score = parseFloat(record.v2_score);
      else if (record.predicted_score) score = parseFloat(record.predicted_score);
      else if (record.rating) score = parseFloat(record.rating);

      const segment = record.segmento || record.segment || '';

      return {
        ...record,
        heatmap_category: determineHeatmapCategory(score),
        suggested_owner: determineOwner(segment)
      };
    });

    const summary = {
      total: rankedLeads.length,
      hot: rankedLeads.filter(l => l.heatmap_category.includes('HOT')).length,
      warm: rankedLeads.filter(l => l.heatmap_category.includes('WARM')).length,
      cold: rankedLeads.filter(l => l.heatmap_category.includes('COLD')).length,
      marcio: rankedLeads.filter(l => l.suggested_owner === 'Márcio').length,
      vanessa: rankedLeads.filter(l => l.suggested_owner === 'Vanessa').length,
      unassigned: rankedLeads.filter(l => l.suggested_owner === 'Unassigned').length
    };

    const outputContent = stringify(rankedLeads, { header: true });
    fs.writeFileSync(OUTPUT_FILE, outputContent);

    const mdContent = `# Lead Ranking Summary Report

**Total Leads Processed:** ${summary.total}

## 🔥 Heatmap Distribution
| Category | Count | Percentage |
|----------|-------|------------|
| **HOT 🔥** | ${summary.hot} | ${((summary.hot / summary.total) * 100).toFixed(1)}% |
| **WARM ⚠️** | ${summary.warm} | ${((summary.warm / summary.total) * 100).toFixed(1)}% |
| **COLD ❄️** | ${summary.cold} | ${((summary.cold / summary.total) * 100).toFixed(1)}% |

## 👤 Ownership Assignment Strategy
- **Márcio (Manufacturing & Industrial Focus):** ${summary.marcio} leads
- **Vanessa (Commercial & Products Focus):** ${summary.vanessa} leads
- **Unassigned:** ${summary.unassigned} leads

## ℹ️ Generation Info
Generated by: \`scripts/rank_leads.js\` (CJS)
Date: ${new Date().toISOString()}
`;

    fs.writeFileSync(SUMMARY_FILE, mdContent);
  } catch (error) {
    fs.writeFileSync(ERROR_FILE, `Runtime Error: ${error.message}\nStack: ${error.stack}`);
  }
}

main();
